import {
    SiCss3,
    SiGit,
    SiHtml5,
    SiJavascript,
    SiLaravel,
    SiMongodb,
    SiMysql,
    SiNodedotjs,
    SiReact,
    SiSass,
    SiGnometerminal,
    SiNextdotjs,
    SiExpress,
    SiPhp,
    SiFigma,
    SiAdobexd,
    SiWordpress,
    SiWebpack,
} from 'react-icons/si'

export const Stack = [
    { id: 3, element: <SiHtml5 size={50} /> },
    { id: 1, element: <SiCss3 size={50} /> },
    { id: 10, element: <SiSass size={50} /> },
    { id: 4, element: <SiJavascript size={50} /> },
    { id: 9, element: <SiReact size={50} /> },
    { id: 12, element: <SiNextdotjs size={50} /> },
    { id: 7, element: <SiMysql size={50} /> },
    { id: 6, element: <SiMongodb size={50} /> },
    { id: 13, element: <SiExpress size={50} /> },
    { id: 8, element: <SiNodedotjs size={50} /> },
    { id: 14, element: <SiPhp size={50} /> },
    { id: 5, element: <SiLaravel size={50} /> },
    { id: 7, element: <SiWordpress size={50} /> },
    { id: 18, element: <SiWebpack size={50} /> },
    { id: 2, element: <SiGit size={50} /> },
    { id: 11, element: <SiGnometerminal size={50} /> },
    { id: 15, element: <SiFigma size={50} /> },
    { id: 16, element: <SiAdobexd size={50} /> },
]
