import { Navbar } from '@/components/Navbar'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    const dark = false
    return (
        <html lang="en">
            <body className={dark ? 'dark' : 'light'}>
                <Navbar />
                {children}
            </body>
        </html>
    )
}
